#!/usr/bin/env bash

# cp /autograder/submission/creditcard.py /autograder/source/creditcard.py
# cp /autograder/submission/creditcard_part1.py /autograder/source/creditcard_part1.py

cp -a /autograder/submission/. /autograder/source/

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json

python3 creditcard.py << EOF
100000
EOF

python3 creditcard_tester.py


